### ISSUE TITLE
verify_partial_doubles = false required for rspec mocks

### ISSUE THREAD

**Issue by gsreynolds** [nessche/kaminari-rspec#5]
rspec-core project initialiser now sets `mocks.verify_partial_doubles = true`. https://github.com/rspec/rspec-core/blob/7c5d508bebf64c7f00b9d7d63ad1114ef481914c/lib/rspec/core/project_initializer/spec/spec_helper.rb#L40

This breaks rspec mocking in kaminari-rspec with failure/error: "does not implement: total_count".

The below is required to workaround this. Either this needs added to the README advising the user to create the below in spec/support and config.include it for view tests, or needs to be included as part of the test helper when using rspec-mocks.

``` ruby
  RSpec.configure do |config|
    config.mock_with :rspec do |mocks|
      mocks.verify_partial_doubles = false
    end
  end
```

**Comment by nessche** [comment]
Hi,
I would leave the workaround as a last resort, as I don't want to turn off an otherwise useful feature. So I updated my test rails application to see if I could recreate the failure, but my specs kept passing.

Could you kindly post an example of a spec that raises that behaviour?

Thanks!

**Comment by nessche** [comment]
Never mind, I managed to recreate the failure.

**Comment by gsreynolds** [comment]
Excellent. I'd agree the workaround is probably a last resort but the issue is obviously that the methods don't exist on the resource e.g. an array of two records such as from FactoryGirl.create_pair, so stubbing their returns will fail when `mocks.verify_partial_doubles = true`

``` ruby
RSpec.describe 'addresses/index', type: :view do

  let(:created_addresses) { create_pair(:address) }

  before(:each) do
    assign(:addresses, stub_pagination(created_addresses))
  end

  it 'renders a list of addresses' do
    render
    <snip>
  end

end
```

Somewhat related discussion here: https://github.com/rspec/rspec-rails/issues/1076

**Comment by nessche** [comment]
I think I have a neat solution for this, but as this is strictly BBD (before bed development), I have to wait until tonight to test it completely....

In a nutshell, unless the object passed to stub_pagination responds to pagination methods (`current_page`, `total_count`, etc...), I will invoke `Kaminary.paginate_array` on the object itself, and then I will stub the extended array returned by the `paginate_array` method.

This way the double verification should succeed as the doubled object indeed implements all the needed methods.

**Comment by gsreynolds** [comment]
Neat indeed! :+1: 

Looking forward to trying it out :)

**Comment by nessche** [comment]
I have just pushed the changes to the repo, it would be great if you could check that they work for you, before releasing the gem as 0.16.1

**Comment by gsreynolds** [comment]
That's fixed it for me, thanks!

**Comment by nessche** [comment]
I just released the new version of the gem. Feel free to reopen this issue, or create a new one if more problems surface. Thanks for your feedback!
